# Generated by Django 3.1.3 on 2020-12-09 14:27

from django.db import migrations, models
import edu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100)),
                ('sellername', models.CharField(max_length=100)),
                ('sellerno', models.CharField(default=0, max_length=10, null=True)),
                ('selleremail', models.EmailField(max_length=75)),
                ('sellprice', models.IntegerField(default=0)),
                ('orgprice', models.IntegerField(default=0)),
                ('image', models.URLField()),
                ('quantity', models.IntegerField(default=1)),
                ('overview', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=75)),
                ('mobno', models.CharField(default=0, max_length=10, null=True)),
                ('major', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('fees', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('image', models.URLField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=75)),
                ('mobno', models.CharField(default=0, max_length=10, null=True)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('overview', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=edu.models.get_image_path)),
                ('email', models.EmailField(max_length=75)),
                ('tchrname', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('course_id', models.IntegerField(default=0)),
                ('course_mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Both', 'Both')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='enrollcontact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=75)),
                ('mobno', models.CharField(default=0, max_length=10, null=True)),
                ('coursename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='epcourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(default=0)),
                ('video', models.FileField(upload_to=edu.models.get_video_path)),
                ('ep_overview', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'epcourse',
                'verbose_name_plural': 'epcourse',
            },
        ),
        migrations.CreateModel(
            name='extuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40)),
                ('is_student', models.BooleanField(default=False)),
                ('is_school', models.BooleanField(default=False)),
                ('is_institute', models.BooleanField(default=False)),
                ('is_tutor', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('is_seller', models.BooleanField(default=False)),
                ('is_college', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('courses', models.CharField(max_length=200)),
                ('years', models.IntegerField(default=0)),
                ('enroll', models.IntegerField(default=0)),
                ('foundername', models.CharField(max_length=75)),
                ('mobno', models.CharField(default=0, max_length=10, null=True)),
                ('website', models.URLField()),
                ('staff', models.IntegerField(default=1)),
                ('image', models.URLField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=75)),
                ('mobno', models.CharField(default=0, max_length=10, null=True)),
                ('board', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('tillclass', models.IntegerField(default=0)),
                ('medium', models.CharField(max_length=100)),
                ('fees', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('image', models.URLField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='spaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('rooms', models.IntegerField(default=1)),
                ('equip', models.CharField(max_length=200)),
                ('hours', models.IntegerField(default=1)),
                ('charge', models.IntegerField(default=0)),
                ('sellername', models.CharField(max_length=100)),
                ('sellerno', models.CharField(default=0, max_length=10, null=True)),
                ('selleremail', models.EmailField(max_length=75)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=75)),
                ('mobno', models.CharField(default=0, max_length=10, null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(default=0)),
                ('hours', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('image', models.URLField()),
                ('days', models.IntegerField(default=0)),
            ],
        ),
    ]
